import { Logger } from '@nestjs/common';
import { PrismaClient, type AppliesTo, type GarmentSlot, type Season } from '@prisma/client';

/**
 * Seed del catálogo de tipos de prenda.
 *
 * `appliesTo` ordena y sugiere; **nunca** excluye: cualquier usuario puede
 * registrar cualquier tipo. Las señales climáticas son el rango de temperatura
 * en el que la prenda resulta cómoda, no una regla dura — el motor de la Fase 2
 * las usa como preferencia blanda salvo incompatibilidad evidente.
 *
 * Es idempotente: cada tipo se identifica por `slug` y se hace upsert, así que
 * volver a correrlo actualiza el catálogo sin duplicar ni romper las prendas ya
 * creadas por los usuarios.
 */

const prisma = new PrismaClient();
const logger = new Logger('seed');

const allSeasons: Season[] = ['SPRING', 'SUMMER', 'AUTUMN', 'WINTER'];
const warmSeasons: Season[] = ['SPRING', 'SUMMER'];
const coldSeasons: Season[] = ['AUTUMN', 'WINTER'];

interface IGarmentTypeSeed {
  slug: string;
  name: string;
  slot: GarmentSlot;
  appliesTo: AppliesTo;
  /** 1 = muy casual, 5 = muy formal. */
  defaultFormality: number;
  typicalSeasons: Season[];
  defaultWeatherMinC?: number;
  defaultWeatherMaxC?: number;
}

const garmentTypes: IGarmentTypeSeed[] = [
  // -- TOP ------------------------------------------------------------------
  {
    slug: 'camiseta',
    name: 'Camiseta',
    slot: 'TOP',
    appliesTo: 'BOTH',
    defaultFormality: 1,
    typicalSeasons: allSeasons,
    defaultWeatherMinC: 16,
    defaultWeatherMaxC: 40,
  },
  {
    slug: 'camiseta-manga-larga',
    name: 'Camiseta de manga larga',
    slot: 'TOP',
    appliesTo: 'BOTH',
    defaultFormality: 2,
    typicalSeasons: allSeasons,
    defaultWeatherMinC: 10,
    defaultWeatherMaxC: 26,
  },
  {
    slug: 'camiseta-sin-mangas',
    name: 'Camiseta sin mangas',
    slot: 'TOP',
    appliesTo: 'BOTH',
    defaultFormality: 1,
    typicalSeasons: warmSeasons,
    defaultWeatherMinC: 24,
    defaultWeatherMaxC: 42,
  },
  {
    slug: 'polo',
    name: 'Polo',
    slot: 'TOP',
    appliesTo: 'BOTH',
    defaultFormality: 2,
    typicalSeasons: allSeasons,
    defaultWeatherMinC: 16,
    defaultWeatherMaxC: 34,
  },
  {
    slug: 'camisa-casual',
    name: 'Camisa casual',
    slot: 'TOP',
    appliesTo: 'BOTH',
    defaultFormality: 3,
    typicalSeasons: allSeasons,
    defaultWeatherMinC: 12,
    defaultWeatherMaxC: 32,
  },
  {
    slug: 'camisa-formal',
    name: 'Camisa formal',
    slot: 'TOP',
    appliesTo: 'BOTH',
    defaultFormality: 4,
    typicalSeasons: allSeasons,
    defaultWeatherMinC: 12,
    defaultWeatherMaxC: 32,
  },
  {
    slug: 'camisa-lino',
    name: 'Camisa de lino',
    slot: 'TOP',
    appliesTo: 'BOTH',
    defaultFormality: 3,
    typicalSeasons: warmSeasons,
    defaultWeatherMinC: 20,
    defaultWeatherMaxC: 40,
  },
  {
    slug: 'blusa',
    name: 'Blusa',
    slot: 'TOP',
    appliesTo: 'FEMALE',
    defaultFormality: 3,
    typicalSeasons: allSeasons,
    defaultWeatherMinC: 16,
    defaultWeatherMaxC: 34,
  },
  {
    slug: 'top',
    name: 'Top',
    slot: 'TOP',
    appliesTo: 'FEMALE',
    defaultFormality: 2,
    typicalSeasons: warmSeasons,
    defaultWeatherMinC: 22,
    defaultWeatherMaxC: 42,
  },
  {
    slug: 'body',
    name: 'Body',
    slot: 'TOP',
    appliesTo: 'FEMALE',
    defaultFormality: 3,
    typicalSeasons: allSeasons,
    defaultWeatherMinC: 18,
    defaultWeatherMaxC: 34,
  },

  // -- MID_LAYER ------------------------------------------------------------
  {
    slug: 'sueter',
    name: 'Suéter',
    slot: 'MID_LAYER',
    appliesTo: 'BOTH',
    defaultFormality: 3,
    typicalSeasons: coldSeasons,
    defaultWeatherMinC: 2,
    defaultWeatherMaxC: 20,
  },
  {
    slug: 'cardigan',
    name: 'Cárdigan',
    slot: 'MID_LAYER',
    appliesTo: 'BOTH',
    defaultFormality: 3,
    typicalSeasons: coldSeasons,
    defaultWeatherMinC: 8,
    defaultWeatherMaxC: 22,
  },
  {
    slug: 'sudadera',
    name: 'Sudadera',
    slot: 'MID_LAYER',
    appliesTo: 'BOTH',
    defaultFormality: 1,
    typicalSeasons: coldSeasons,
    defaultWeatherMinC: 8,
    defaultWeatherMaxC: 22,
  },
  {
    slug: 'sudadera-capucha',
    name: 'Sudadera con capucha',
    slot: 'MID_LAYER',
    appliesTo: 'BOTH',
    defaultFormality: 1,
    typicalSeasons: coldSeasons,
    defaultWeatherMinC: 6,
    defaultWeatherMaxC: 22,
  },
  {
    slug: 'chaleco',
    name: 'Chaleco',
    slot: 'MID_LAYER',
    appliesTo: 'BOTH',
    defaultFormality: 3,
    typicalSeasons: coldSeasons,
    defaultWeatherMinC: 6,
    defaultWeatherMaxC: 20,
  },
  {
    slug: 'blazer',
    name: 'Blazer',
    slot: 'MID_LAYER',
    appliesTo: 'BOTH',
    defaultFormality: 4,
    typicalSeasons: allSeasons,
    defaultWeatherMinC: 10,
    defaultWeatherMaxC: 26,
  },

  // -- OUTERWEAR ------------------------------------------------------------
  {
    slug: 'chaqueta-denim',
    name: 'Chaqueta de jean',
    slot: 'OUTERWEAR',
    appliesTo: 'BOTH',
    defaultFormality: 2,
    typicalSeasons: allSeasons,
    defaultWeatherMinC: 10,
    defaultWeatherMaxC: 22,
  },
  {
    slug: 'chaqueta-cuero',
    name: 'Chaqueta de cuero',
    slot: 'OUTERWEAR',
    appliesTo: 'BOTH',
    defaultFormality: 3,
    typicalSeasons: coldSeasons,
    defaultWeatherMinC: 4,
    defaultWeatherMaxC: 20,
  },
  {
    slug: 'chaqueta-bomber',
    name: 'Chaqueta bomber',
    slot: 'OUTERWEAR',
    appliesTo: 'BOTH',
    defaultFormality: 2,
    typicalSeasons: coldSeasons,
    defaultWeatherMinC: 6,
    defaultWeatherMaxC: 20,
  },
  {
    slug: 'cortavientos',
    name: 'Cortavientos',
    slot: 'OUTERWEAR',
    appliesTo: 'BOTH',
    defaultFormality: 1,
    typicalSeasons: allSeasons,
    defaultWeatherMinC: 8,
    defaultWeatherMaxC: 24,
  },
  {
    slug: 'impermeable',
    name: 'Impermeable',
    slot: 'OUTERWEAR',
    appliesTo: 'BOTH',
    defaultFormality: 2,
    typicalSeasons: allSeasons,
    defaultWeatherMinC: 6,
    defaultWeatherMaxC: 24,
  },
  {
    slug: 'gabardina',
    name: 'Gabardina',
    slot: 'OUTERWEAR',
    appliesTo: 'BOTH',
    defaultFormality: 4,
    typicalSeasons: coldSeasons,
    defaultWeatherMinC: 4,
    defaultWeatherMaxC: 18,
  },
  {
    slug: 'abrigo',
    name: 'Abrigo',
    slot: 'OUTERWEAR',
    appliesTo: 'BOTH',
    defaultFormality: 4,
    typicalSeasons: coldSeasons,
    defaultWeatherMinC: -5,
    defaultWeatherMaxC: 14,
  },
  {
    slug: 'chaqueta-acolchada',
    name: 'Chaqueta acolchada',
    slot: 'OUTERWEAR',
    appliesTo: 'BOTH',
    defaultFormality: 2,
    typicalSeasons: coldSeasons,
    defaultWeatherMinC: -8,
    defaultWeatherMaxC: 12,
  },
  {
    slug: 'parka',
    name: 'Parka',
    slot: 'OUTERWEAR',
    appliesTo: 'BOTH',
    defaultFormality: 2,
    typicalSeasons: coldSeasons,
    defaultWeatherMinC: -10,
    defaultWeatherMaxC: 10,
  },

  // -- BOTTOM ---------------------------------------------------------------
  {
    slug: 'jean',
    name: 'Jean',
    slot: 'BOTTOM',
    appliesTo: 'BOTH',
    defaultFormality: 2,
    typicalSeasons: allSeasons,
    defaultWeatherMinC: 5,
    defaultWeatherMaxC: 30,
  },
  {
    slug: 'chino',
    name: 'Pantalón chino',
    slot: 'BOTTOM',
    appliesTo: 'BOTH',
    defaultFormality: 3,
    typicalSeasons: allSeasons,
    defaultWeatherMinC: 8,
    defaultWeatherMaxC: 30,
  },
  {
    slug: 'pantalon-vestir',
    name: 'Pantalón de vestir',
    slot: 'BOTTOM',
    appliesTo: 'BOTH',
    defaultFormality: 5,
    typicalSeasons: allSeasons,
    defaultWeatherMinC: 8,
    defaultWeatherMaxC: 30,
  },
  {
    slug: 'pantalon-lino',
    name: 'Pantalón de lino',
    slot: 'BOTTOM',
    appliesTo: 'BOTH',
    defaultFormality: 3,
    typicalSeasons: warmSeasons,
    defaultWeatherMinC: 20,
    defaultWeatherMaxC: 40,
  },
  {
    slug: 'pantalon-cargo',
    name: 'Pantalón cargo',
    slot: 'BOTTOM',
    appliesTo: 'BOTH',
    defaultFormality: 1,
    typicalSeasons: allSeasons,
    defaultWeatherMinC: 8,
    defaultWeatherMaxC: 28,
  },
  {
    slug: 'jogger',
    name: 'Jogger',
    slot: 'BOTTOM',
    appliesTo: 'BOTH',
    defaultFormality: 1,
    typicalSeasons: allSeasons,
    defaultWeatherMinC: 8,
    defaultWeatherMaxC: 26,
  },
  {
    slug: 'short',
    name: 'Short',
    slot: 'BOTTOM',
    appliesTo: 'BOTH',
    defaultFormality: 1,
    typicalSeasons: warmSeasons,
    defaultWeatherMinC: 22,
    defaultWeatherMaxC: 42,
  },
  {
    slug: 'bermuda',
    name: 'Bermuda',
    slot: 'BOTTOM',
    appliesTo: 'BOTH',
    defaultFormality: 2,
    typicalSeasons: warmSeasons,
    defaultWeatherMinC: 20,
    defaultWeatherMaxC: 40,
  },
  {
    slug: 'legging',
    name: 'Legging',
    slot: 'BOTTOM',
    appliesTo: 'BOTH',
    defaultFormality: 1,
    typicalSeasons: allSeasons,
    defaultWeatherMinC: 8,
    defaultWeatherMaxC: 26,
  },
  {
    slug: 'falda-corta',
    name: 'Falda corta',
    slot: 'BOTTOM',
    appliesTo: 'FEMALE',
    defaultFormality: 2,
    typicalSeasons: warmSeasons,
    defaultWeatherMinC: 20,
    defaultWeatherMaxC: 40,
  },
  {
    slug: 'falda-midi',
    name: 'Falda midi',
    slot: 'BOTTOM',
    appliesTo: 'FEMALE',
    defaultFormality: 3,
    typicalSeasons: allSeasons,
    defaultWeatherMinC: 14,
    defaultWeatherMaxC: 34,
  },
  {
    slug: 'falda-larga',
    name: 'Falda larga',
    slot: 'BOTTOM',
    appliesTo: 'FEMALE',
    defaultFormality: 3,
    typicalSeasons: allSeasons,
    defaultWeatherMinC: 12,
    defaultWeatherMaxC: 34,
  },

  // -- FULL_BODY ------------------------------------------------------------
  {
    slug: 'vestido-casual',
    name: 'Vestido casual',
    slot: 'FULL_BODY',
    appliesTo: 'FEMALE',
    defaultFormality: 2,
    typicalSeasons: warmSeasons,
    defaultWeatherMinC: 18,
    defaultWeatherMaxC: 38,
  },
  {
    slug: 'vestido-coctel',
    name: 'Vestido de cóctel',
    slot: 'FULL_BODY',
    appliesTo: 'FEMALE',
    defaultFormality: 5,
    typicalSeasons: allSeasons,
    defaultWeatherMinC: 16,
    defaultWeatherMaxC: 34,
  },
  {
    slug: 'vestido-largo',
    name: 'Vestido largo',
    slot: 'FULL_BODY',
    appliesTo: 'FEMALE',
    defaultFormality: 4,
    typicalSeasons: allSeasons,
    defaultWeatherMinC: 16,
    defaultWeatherMaxC: 36,
  },
  {
    slug: 'jumpsuit',
    name: 'Jumpsuit',
    slot: 'FULL_BODY',
    appliesTo: 'BOTH',
    defaultFormality: 3,
    typicalSeasons: allSeasons,
    defaultWeatherMinC: 16,
    defaultWeatherMaxC: 34,
  },
  {
    slug: 'overol',
    name: 'Overol',
    slot: 'FULL_BODY',
    appliesTo: 'BOTH',
    defaultFormality: 1,
    typicalSeasons: allSeasons,
    defaultWeatherMinC: 12,
    defaultWeatherMaxC: 30,
  },
  {
    slug: 'traje',
    name: 'Traje completo',
    slot: 'FULL_BODY',
    appliesTo: 'BOTH',
    defaultFormality: 5,
    typicalSeasons: allSeasons,
    defaultWeatherMinC: 10,
    defaultWeatherMaxC: 30,
  },

  // -- FOOTWEAR -------------------------------------------------------------
  {
    slug: 'tenis',
    name: 'Tenis',
    slot: 'FOOTWEAR',
    appliesTo: 'BOTH',
    defaultFormality: 2,
    typicalSeasons: allSeasons,
    defaultWeatherMinC: 5,
    defaultWeatherMaxC: 38,
  },
  {
    slug: 'tenis-deportivos',
    name: 'Tenis deportivos',
    slot: 'FOOTWEAR',
    appliesTo: 'BOTH',
    defaultFormality: 1,
    typicalSeasons: allSeasons,
    defaultWeatherMinC: 5,
    defaultWeatherMaxC: 38,
  },
  {
    slug: 'mocasines',
    name: 'Mocasines',
    slot: 'FOOTWEAR',
    appliesTo: 'BOTH',
    defaultFormality: 4,
    typicalSeasons: allSeasons,
    defaultWeatherMinC: 10,
    defaultWeatherMaxC: 34,
  },
  {
    slug: 'zapatos-vestir',
    name: 'Zapatos de vestir',
    slot: 'FOOTWEAR',
    appliesTo: 'BOTH',
    defaultFormality: 5,
    typicalSeasons: allSeasons,
    defaultWeatherMinC: 8,
    defaultWeatherMaxC: 34,
  },
  {
    slug: 'botines',
    name: 'Botines',
    slot: 'FOOTWEAR',
    appliesTo: 'BOTH',
    defaultFormality: 3,
    typicalSeasons: coldSeasons,
    defaultWeatherMinC: 0,
    defaultWeatherMaxC: 22,
  },
  {
    slug: 'botas',
    name: 'Botas',
    slot: 'FOOTWEAR',
    appliesTo: 'BOTH',
    defaultFormality: 3,
    typicalSeasons: coldSeasons,
    defaultWeatherMinC: -5,
    defaultWeatherMaxC: 18,
  },
  {
    slug: 'sandalias',
    name: 'Sandalias',
    slot: 'FOOTWEAR',
    appliesTo: 'BOTH',
    defaultFormality: 1,
    typicalSeasons: warmSeasons,
    defaultWeatherMinC: 22,
    defaultWeatherMaxC: 42,
  },
  {
    slug: 'alpargatas',
    name: 'Alpargatas',
    slot: 'FOOTWEAR',
    appliesTo: 'BOTH',
    defaultFormality: 2,
    typicalSeasons: warmSeasons,
    defaultWeatherMinC: 18,
    defaultWeatherMaxC: 38,
  },
  {
    slug: 'tacones',
    name: 'Tacones',
    slot: 'FOOTWEAR',
    appliesTo: 'FEMALE',
    defaultFormality: 5,
    typicalSeasons: allSeasons,
    defaultWeatherMinC: 12,
    defaultWeatherMaxC: 34,
  },
  {
    slug: 'bailarinas',
    name: 'Bailarinas',
    slot: 'FOOTWEAR',
    appliesTo: 'FEMALE',
    defaultFormality: 3,
    typicalSeasons: allSeasons,
    defaultWeatherMinC: 14,
    defaultWeatherMaxC: 34,
  },

  // -- ACCESSORY ------------------------------------------------------------
  {
    slug: 'cinturon',
    name: 'Cinturón',
    slot: 'ACCESSORY',
    appliesTo: 'BOTH',
    defaultFormality: 3,
    typicalSeasons: allSeasons,
  },
  {
    slug: 'corbata',
    name: 'Corbata',
    slot: 'ACCESSORY',
    appliesTo: 'BOTH',
    defaultFormality: 5,
    typicalSeasons: allSeasons,
  },
  {
    slug: 'gorra',
    name: 'Gorra',
    slot: 'ACCESSORY',
    appliesTo: 'BOTH',
    defaultFormality: 1,
    typicalSeasons: allSeasons,
  },
  {
    slug: 'sombrero',
    name: 'Sombrero',
    slot: 'ACCESSORY',
    appliesTo: 'BOTH',
    defaultFormality: 2,
    typicalSeasons: allSeasons,
  },
  {
    slug: 'bufanda',
    name: 'Bufanda',
    slot: 'ACCESSORY',
    appliesTo: 'BOTH',
    defaultFormality: 2,
    typicalSeasons: coldSeasons,
    defaultWeatherMinC: -10,
    defaultWeatherMaxC: 16,
  },
  {
    slug: 'gafas-sol',
    name: 'Gafas de sol',
    slot: 'ACCESSORY',
    appliesTo: 'BOTH',
    defaultFormality: 2,
    typicalSeasons: allSeasons,
  },
  {
    slug: 'reloj',
    name: 'Reloj',
    slot: 'ACCESSORY',
    appliesTo: 'BOTH',
    defaultFormality: 3,
    typicalSeasons: allSeasons,
  },
  {
    slug: 'collar',
    name: 'Collar',
    slot: 'ACCESSORY',
    appliesTo: 'BOTH',
    defaultFormality: 3,
    typicalSeasons: allSeasons,
  },
  {
    slug: 'bolso',
    name: 'Bolso',
    slot: 'ACCESSORY',
    appliesTo: 'BOTH',
    defaultFormality: 3,
    typicalSeasons: allSeasons,
  },
  {
    slug: 'mochila',
    name: 'Mochila',
    slot: 'ACCESSORY',
    appliesTo: 'BOTH',
    defaultFormality: 1,
    typicalSeasons: allSeasons,
  },
  {
    slug: 'panuelo',
    name: 'Pañuelo',
    slot: 'ACCESSORY',
    appliesTo: 'BOTH',
    defaultFormality: 3,
    typicalSeasons: allSeasons,
  },
];

/**
 * Inserta o actualiza el catálogo completo respetando el orden del array.
 * @returns {Promise<void>}
 */
async function seedGarmentTypes(): Promise<void> {
  for (const [index, garmentType] of garmentTypes.entries()) {
    const data = {
      name: garmentType.name,
      slot: garmentType.slot,
      appliesTo: garmentType.appliesTo,
      defaultFormality: garmentType.defaultFormality,
      typicalSeasons: garmentType.typicalSeasons,
      defaultWeatherMinC: garmentType.defaultWeatherMinC ?? null,
      defaultWeatherMaxC: garmentType.defaultWeatherMaxC ?? null,
      sortOrder: index,
    };
    await prisma.garmentType.upsert({
      where: { slug: garmentType.slug },
      create: { slug: garmentType.slug, ...data },
      update: data,
    });
  }
}

seedGarmentTypes()
  .then(async () => {
    logger.log(
      `seedGarmentTypes - catálogo de tipos de prenda al día (${garmentTypes.length} tipos)`,
    );
    await prisma.$disconnect();
  })
  .catch(async (error: unknown) => {
    logger.error(
      'seedGarmentTypes - error sembrando el catálogo',
      error instanceof Error ? error.message : String(error),
    );
    await prisma.$disconnect();
    process.exit(1);
  });
